name: Create Version
on:
  pull_request:
    types:
      - closed
jobs:
  create-version:
    if: |
      github.event.pull_request.merged == true && 
      (
        startsWith(github.event.pull_request.head.ref, 'feature/') ||
        startsWith(github.event.pull_request.head.ref, 'bug/') ||
        startsWith(github.event.pull_request.head.ref, 'fix/')
      )
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.base.ref}}
          fetch-depth: 0
      - name: Show base and merged branch
        run: |
          echo "BASE=${{github.event.pull_request.base.ref}}"
          echo "BASE=${{github.event.pull_request.base.ref}}" >> $GITHUB_ENV
          echo "MERGED=${{github.event.pull_request.head.ref}}"
          echo "MERGED=${{github.event.pull_request.head.ref}}" >> $GITHUB_ENV
      - name: Update VERSION
        run: |
          # Check version file
          if [ ! -f "VERSION" ]; then
            echo "VERSION file not found!"
            exit 1
          fi
          # Load current version
          OLD_VERSION=$(cat VERSION)
          if ! [[ "$OLD_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "VERSION file has invalid format: $OLD_VERSION"
            echo "0.0.0" > VERSION
            OLD_VERSION="0.0.0"
          fi
          IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD_VERSION"
          UPDATED=false
          # Determine update logic based on branch name
          if [[ "${{env.MERGED}}" =~ ^(bug|fix) ]]; then
            PATCH=$((PATCH + 1))
            UPDATED=true
          elif [[ "${{env.MERGED}}" =~ ^(feature) ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0  # Reset PATCH when MINOR is incremented
            UPDATED=true
          else
            echo "No version update needed for branch: ${{env.MERGED}}"
            exit 0
          fi
          # Write updated version back to file
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "Updated VERSION from $OLD_VERSION to $NEW_VERSION"
          echo "OLD_VERSION=$OLD_VERSION" >> $GITHUB_ENV
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "UPDATED=$UPDATED" >> $GITHUB_ENV
      - name: Create Release Branch and Commit Changes
        if: ${{env.UPDATED == 'true'}}
        run: |
          RELEASE_BRANCH="release/${{env.NEW_VERSION}}"
          git checkout -b $RELEASE_BRANCH
          if [ ! -f "docs/${{env.MERGED}}.md" ]; then
            echo "docs/${{env.MERGED}}.md file is not found"
            exit 1
          fi
          echo "${{env.NEW_VERSION}}" > VERSION
          CHANGES=$(cat docs/${{env.MERGED}}.md)
          echo "$CHANGES" > docs/VERSION/${{env.NEW_VERSION}}.md
          git config user.name "${{vars.ACTION_USERNAME}}"
          git config user.email "${{vars.ACTION_USEREMAIL}}"
          git add VERSION
          git add docs/VERSION/${{env.NEW_VERSION}}.md
          git commit -m "Update VERSION from $OLD_VERSION to ${{env.NEW_VERSION}}"
          git push origin $RELEASE_BRANCH
      - name: Create Pull Request
        if: ${{env.UPDATED == 'true'}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          RELEASE_BRANCH="release/${{env.NEW_VERSION}}"
          TITLE="Release - ${{env.NEW_VERSION}}"
          BODY=$(cat docs/VERSION/${{env.NEW_VERSION}}.md | jq -Rs .)
          URL="https://api.github.com/repos/${{github.repository}}/pulls"
          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"title\":\"$TITLE\",\"head\":\"$RELEASE_BRANCH\",\"base\":\"${{github.event.pull_request.base.ref}}\",\"body\":\"$BODY\"}" \
            $URL

